# Generated by Django 4.2.4 on 2023-08-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='compcompleted',
        ),
    ]
