# Generated by Django 4.2.4 on 2023-08-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_name_todo_title_remove_todo_compcompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
