# Generated by Django 4.2.4 on 2023-08-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_status_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='spent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
